// src/lib/router/Router.vue
<script setup>
import { onBeforeUnmount, onMounted, shallowRef, watch } from 'vue';

const props = defineProps({ routes: { type: Object, required: true } });
const currentPath = shallowRef(window.location.pathname);
const CurrentComponent = shallowRef(null);

async function resolveCurrentComponent(path) {
  const routeEntry = props.routes[path] || props.routes['/'];
  if (typeof routeEntry !== 'function') {
    CurrentComponent.value = routeEntry || null;
    return;
  }

  try {
    const module = await routeEntry();
    CurrentComponent.value = module?.default || null;
  } catch {
    CurrentComponent.value = null;
  }
}

function navigate(path) {
  window.history.pushState({}, '', path);
  window.scrollTo(0, 0);
  currentPath.value = path;
}

const handlePopState = () => {
  currentPath.value = window.location.pathname;
};

const handleClick = (event) => {
  if (event.target.tagName === 'A' && event.target.getAttribute('href')?.startsWith('/')) {
    event.preventDefault();
    navigate(event.target.getAttribute('href'));
  }
};

onMounted(() => {
  window.addEventListener('popstate', handlePopState);
  window.addEventListener('click', handleClick);
});
onBeforeUnmount(() => {
  window.removeEventListener('popstate', handlePopState);
  window.removeEventListener('click', handleClick);
});
watch(currentPath, resolveCurrentComponent, { immediate: true });
</script>

<template>
<component :is="CurrentComponent" v-if="CurrentComponent" />
</template>

// src/lib/router/Router.svelte
<!-- DO NOT TOUCH THIS FILE AT ANY COST -->
<!-- unless the router is broken 👉👈 -->

<script>
  export function routeTo(path) {
    window.history.pushState({}, "", path);
    window.scrollTo(0, 0);
    window.dispatchEvent(new PopStateEvent("popstate"));
  }

  let { routes } = $props();

  let currentPath = $state(window.location.pathname);
  let CurrentComponent = $state(null);

  async function resolveCurrentComponent(path) {
    const routeEntry = routes[path] || routes["/"];

    if (typeof routeEntry === "function") {
      try {
        const module = await routeEntry();
        CurrentComponent = module?.default || null;
      } catch {
        CurrentComponent = null;
      }
      return;
    }

    CurrentComponent = routeEntry || null;
  }

  function navigate(path) {
    window.history.pushState({}, "", path);
    window.scrollTo(0, 0);
    currentPath = path;
  }

  // Handle back/forward buttons
  $effect(() => {
    const handlePopState = () => {
      currentPath = window.location.pathname;
    };

    window.addEventListener("popstate", handlePopState);

    return () => window.removeEventListener("popstate", handlePopState);
  });

  // Intercept link clicks
  $effect(() => {
    const handleClick = (e) => {
      if (
        e.target.tagName === "A" &&
        e.target.getAttribute("href")?.startsWith("/")
      ) {
        e.preventDefault();
        navigate(e.target.getAttribute("href"));
      }
    };

    window.addEventListener("click", handleClick);

    return () => window.removeEventListener("click", handleClick);
  });

  $effect(() => {
    resolveCurrentComponent(currentPath);
  });
</script>

{#if CurrentComponent}
  <CurrentComponent />
{/if}
